# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MediaApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MediaApp
  pod 'Lightbox'
  pod 'NYTPhotoViewer'
  pod 'Player'
  pod 'SDWebImage'
  pod 'SwifterSwift'
  pod 'VFCabbage' 
end
